services:
  - docker:19-dind

variables:
  VARIABLE_DATA: Gitlab-CI-YAML
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2
  AGENT_NAME: pegasus

stages:
  - build
  - deploy

before_script:
  - export IMAGE=$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  - export WEB_IMAGE=$IMAGE:web
  - echo $IMAGE:web
  - echo $CI_REGISTRY_USER
  - echo $CI_JOB_TOKEN
  - echo $CI_REGISTRY
  - echo WEB_IMAGE
  - echo $CI_REGISTRY_IMAGE
  - echo $DEPLOY_TOKEN
#  - apk add --no-cache openssh-client bash docker-compose
#  - docker-compose version
#  - echo $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME

build:
  image: docker:18.09
  services:
    - docker:18.09-dind   
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  stage: build
  script:
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      - docker build --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') --build-arg GIT_FULL_BRANCH=$(git rev-parse --abbrev-ref HEAD) --build-arg SHORT_COMMIT_HASH=${CI_COMMIT_SHA:0:8} -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE:latest .
      - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main


deploy:
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  stage: deploy
  script:
    - export
    - kubectl config get-contexts
    - kubectl config use-context $CI_PROJECT_PATH:$AGENT_NAME
    - kubectl config set-context --current --namespace=default
    - kubectl get pods
    - kubectl set image deployment/pegasus-ims pegasus-ims=${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} --record
  only:
    - main