port: 11001
image:
  name: registry.gitlab.com/vuduc047/pegasus-ams
  tag: latest
context:
  path: /ams/api
log:
  level:
    root: info
    spring: info
    app: debug
kubernetes:
  imagePullPolicy: Always
  replicaCount: 1
appUrl:
  ui: http://sylveron.com
  ims: http://pegasus-ims-service/ims/api
postgresql:
  datasource:
    dbUrl: jdbc:postgresql://pegasus-shared-postgres:5432/pegasusdb
    username: pegasus002
    password: password123
redis:
  port: 6379
  host: pegasus-shared-redis-master
kafka:
  enable: true
  url: http://sylveron.com:30681
token:
  exp: 40
  unit: MINUTES